language: node_js

node_js:
  - stable

env:
  - DISPLAY=:99.0

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run test

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

deploy:
  provider: npm
  email: "davis_france@hotmail.com"
  api_key: "d59e4d39-40bf-441e-aca8-c121d749a789"
  on:
    tags: true
